# Name of the workflow
name: Model update

# Run on every version update
on:
  push:
    paths:
      - 'packages/regression_model/regression_model/VERSION'

# Automatically create a GitHub Release, with release details specified (the relevant commits)
jobs:
  release:
    name: "model-update"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
